# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ns2Y3JlmNWl9axfW01yGu3SXtgEPUzBE
"""

text = input()

def splitwords(text):
  import re
  text = re.findall(r"\S+", text)
  print(text)

splitwords(text)

